apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: team1-kustomization
  namespace: team1
spec:
  interval: 1m
  path: "./resources"  # Путь к директории с вашими ресурсами
  prune: true
  sourceRef:
    kind: GitRepository
    name: t1-flux-project1
  targetNamespace: team1
